//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironnementNewsApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Api
    {
        public int ID { get; set; }
        public string Img { get; set; }
        public string Lien { get; set; }
    }
}
